#
# .travis.yml contains YAML-formatted (http://www.yaml.org/) instructions
# for building the rebol-server .APK for continuous integration via Travis CI:
#
# http://docs.travis-ci.com/
#
# This file should follow the conventions of the Ren-C project, so see the
# notes in its `.travis.yml` file on indentation and other conventions:
#
# https://github.com/metaeducation/ren-c/blob/master/.travis.yml
#

notifications:
  email: false  # committers are keeping an eye on failures, supposedly!


# Travis defaults to 50; not needed, use 3 (just 1 affects queue notification)
#
# https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth
#
git:
  depth: 3


# Each configured travis instance has its own customized environment variables
# to give it unique behavior.  But there are also global environment keys,
# available to the overall Travis process itself (e.g. deployment)
#
# https://docs.travis-ci.com/user/environment-variables/#Global-Variables
#
env:
  global:
    #
    # See the notes on the Ren-C .travis.yml for these Amazon AWS keys.  The
    # most important thing to note is that the Travis "deploy" feature is not
    # used by this script, but uploads are manual via the `aws` command-line
    # tool, to get more control over the upload ordering and MIME types.
    #
    - secure: 'Bex3tqrlsnv+t3+AJu6nG8bcbfHXeBNWIUUdcEeyB8gWnWnVuBsC5hTw9cUhEWJchJSsV4LeWVL51harzOQRntszyfjeNvPQozCXbTQVGd1tn5Rpt1QKN9VBK007c+ERj9L8JzFkM2HdeVusYY4Bz5tI883DSJkydyJpJp21mG9i8a17bqJsgBW0JmMsMsdv1ilaeb8/Luo8bn0ObIWTTz+4/6RF4XU9UcWLH7I4HlGb3qufR9chWCX7jTT0SLRkEgfudr+KVrY4xIspiPlVwrKvagnOTFcYLxN4JpGOgn1rnCcOxsWo4kE4dwgXZvEn8W2HJmJhzhAHDLkF0S7YhIDQaScJLwSVECI9xu68V5siWdyhzyrSb2K7V8Mtzryjzq1QueCrRRTj7XLY7sx5OxeP//RVMY0Poil5DdB84nI1wezzmT1kj7dkc1Fr1ZqdYSEfCZNd1v+DeRmAf/N70xUyx1tSxAHD96kjDM3lGILIrlt9RLWdeT0BqxQxzaKCowPVgfztH0nzPcoe1DfNfIhG9mEdjeJfLC7hAgc9Dn0KTo/oSwX/TBsTavV+6SPxH1D4q1xVdY9p4G2hS/N1xaqf7ys4DQOPwWZwvhujwGtto4fy7VMvDtX7jI6++0dJe+baG0DetlHvUGKzWpBJgk02k3mREH+9Ui8f7T9vn8Y='
    - secure: 'IlBRG9mRM0BDtb9ZJDKl4QVRjs/e3KxvjEdVS9e8+PlGq+xMDVGQdje9WOED/bhTcoAYabhLKkXY8YZg6rlVj4ecyjjmZRfPA4D9YVMVHZVNldLX9Ed79Kv95dTvFdn6xl9Tbk/CEqtxfDwcN2hZqv9M3TXN2+sKzny6p4ENc8O7sz0Stb4GyFgPdWSIs4SZv/r8/feMgWiUx+q1NFFarMmFsLtKVuiPIyoU6fGW1zZPyh10jKuhi9GYBStcMHIWqvU+9+jbqchMJT1t/1fyEf0fJokNMH2KXCVDbsu7nKhaVZbIxirLdZNicKfzype1uRgzAB/Crpup+TwnINd17HPSqjCnqntuS+pO0mIRcXVhNSE8TG9S8x4N0pgtKYHKyfAjElmjLwPfoMhu5VlZishn6heeUALbQ7y44YwWwG8EoW4PnRFIGg7V4EjlHJkcmDhJWrZX2hVvSGJ72lFhHXFMcr+VKhXWlmK97XdFAz/c/LlSyyrmKtIE6W5kwhJC8bbrpETA/wQ9pP3WEVY28bka24LqI1g0hiDn7cyXae7Ikss36Y8eB/9/00EovCPHw1o+dyenXI10Q8+yorQ42xrjo1bXuYRohCvI+FmV4XFLkJ+c6wDTSKhJTcUhZsQva2F0ipeyqhGQQGkLiZ8BvdoSPHHBx2odikgho9VQZ48='
    - AWS_S3_BUCKET_NAME: 'metaeducation'


# All Travis instances in the following "matrix" will run the same `script:`
# code (found later on in the file).  However, each instance has environment
# variables which can guide that script to behave differently.
#
# Since a prebuilt Rebol is downloaded as part of this process, there is no
# current need for any additional C cross-compilation on ARM to make more
# binaries for the bundle.  However, this configures an environment so that we
# *could* do ARM compilation if it were necessary (to build any added extension
# or extra material intended to be executed in the package.)
#
matrix:
  include:
    #
    # [1] 
    #
    - os: linux
      dist: trusty
      sudo: false  # force new container-based infrastructure
      language: android
      env:
        - NUMBER=1
      addons:
        apt:
          packages:


# The install step occurs before the `script:` step runs.  The language that
# was specified in the `matrix:` entry for each instance will guide certain
# default tools that will be installed.  But you can add custom steps:
#
# https://docs.travis-ci.com/user/customizing-the-build#Customizing-the-Installation-Step
#
# What we do is install the AWS command line tool so we can upload the products
# and control their MIME types.
#
install:
  - |
    # Check PIP installation
    #
    if pip --version; then PIP=pip; fi
    if pip2 --version; then PIP=pip2; fi
    if pip3 --version; then PIP=pip3; fi
    if $PIP --version
    then echo PIP=$PIP
    else echo "!!! PIP NOT FOUND !!!"; exit 1
    fi

  - |
    # Install the AWS command-line tool for uploading to s3 (which we use
    # instead of Travis's `deploy`)
    if $PIP install awscli --upgrade --user
    then echo AWS installed
    else
        echo "!!! AWS not installed !!!"
        exit 1
    fi

    AWS="$(find /Users/travis/Library/Python/ -name aws)"
    if aws --version; then AWS=aws;fi
    if $AWS --version
    then echo AWS=$AWS
    else echo "!!! AWS NOT FOUND !!!"; exit 1
    fi

script:
    - |
      # whatever home directory Travis put us in, build there
      TOP_DIR="$(pwd)"  # https://stackoverflow.com/a/10795195/

    - |
      "${CROSS_PREFIX}gcc" --version  # Output version of gcc for the log

    # Ask for as many parallel builds as the virtual host supports
    - |
      if [[ $TRAVIS_OS_NAME = linux ]]; then
        export MAKE_JOBS="$(nproc)"
      fi

    # Native Development Kit (NDK) is for C/C++ cross-compilation to Android.
    # https://developer.android.com/ndk
    #
    # This is not needed here, but could be if we were doing more building of
    # C code beyond just embedding the already-built Rebol.
    #
    #- |
    #  if [[ $OS_ID = 0.13.2 ]]; then
    #      if [[ $(uname -m) = x86_64 ]]; then
    #          wget https://github.com/giuliolunati/android-travis/releases/download/v1.0.0/android-ndk-r13.tgz
    #          export ANDROID_NDK="${TOP_DIR}/android-ndk-r13"
    #      else
    #          exit 1
    #      fi
    #      tar zxf android-ndk-r13.tgz
    #      echo "$(pwd)"
    #      ls -dl "$(pwd)/android-ndk-r13"
    #      export CROSS_PREFIX="${ANDROID_NDK}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-"
    #      export SYSROOT="${ANDROID_NDK}/platforms/android-19/arch-arm"
    #  fi

    # Grab the abbreviated and full git commit ID into environment variables.
    # The full commit is passed to make to build into the binary, and the
    # abbreviated commit is used to name the executable.
    #
    # http://stackoverflow.com/a/42549385/211160
    #
    # !!! Written this way, this will be the git commit of the rebol-server
    # project, not the commit ID of the embedded Rebol executable.  It is
    # probably the case that the hash of the embedded Rebol makes more sense
    # to use, but this .travis.yml is a work in progress.
    #
    - GIT_COMMIT="$(git show --format="%H" --no-patch)"
    - echo "$GIT_COMMIT"
    - GIT_COMMIT_SHORT="$(git show --format="%h" --no-patch)"
    - echo "$GIT_COMMIT_SHORT"

# BUILD STEP
#
# !!! We technically would like to build variations of the .APK for various
# Android versions.  It appears not possible to make a "universal APK", so we
# would need to call the bash script multiple times, and upload all the build
# products to Amazon AWS.
#
# https://github.com/metaeducation/rebol-server/issues/3

    - |
      PATH=/usr/local/android-sdk/build-tools/25.0.2:$PATH
      bash build.bash

# DEPLOY STEP:

    # check what is left in the build directory...
    - ls

    # Name the executable based on the abbreviated commit, whether it is a
    # debug or release build, and if it was built using C++ or not.  Note that
    # the C++ debug builds have additional runtime checks in the debug
    # build...though there should not be any impact on the release build.
    # (Though there may be additional DLL dependencies regardless.)
    #
    # !!! All Ren-C stakeholders should be using debug builds at this time.
    #
    # Note: -z tests if a variable is undefined
    #
    - NEW_NAME="rebol-server-${GIT_COMMIT_SHORT}"
    - if [[ $DEBUG != none ]]; then NEW_NAME+='-debug'; fi
    - NEW_NAME+='.apk'
    - echo "$NEW_NAME"

    # Move the executable into a directory based on its OS_ID platform.
    # This is because the deploy step is run for each OS and would
    # otherwise overwrite executables in the same location.
    #
    # Note: [[-e]] tests for "existence"
    #
    - mkdir "$OS_ID"
    - |
      mv bin/rebol-server.apk "${OS_ID}/${NEW_NAME}"

    # Web Browsers are picky about the MIME type of some files.  We want to
    # make sure that the right type is chosen:
    #
    # https://stackoverflow.com/a/11643041/211160
    #
    # The `deploy` upload mechanic in Travis has no way to specify this
    # property, so we use the command-line `aws` tool to do the uploads.
    #
    # We also want to control the *order* in which files are uploaded, which
    # Travis's deploy does not support.  For how the keys are kept secure
    # despite publishing this upload script, see:
    #
    # http://stackoverflow.com/a/42547424/211160
    #
    - |
      if [[ ${TRAVIS_BRANCH} != "master" || ${TRAVIS_PULL_REQUEST} != "false" || ${R3_EXIT_STATUS} != 0 ]]
      then exit 0 # skip the deploy step
      fi

      function upload {
        # Note that `;;` is specific to bash's `case`, unrelated to `;`
        case $1 in
          *.apk) OPT_TYPE="--content-type application/vnd.android.package-archive" ;;
          *) OPT_TYPE="" ;;
        esac
        rm -f _
        $AWS s3 cp $1 s3://${AWS_S3_BUCKET_NAME}/travis-builds/$1 $OPT_TYPE
        $AWS s3 cp s3://${AWS_S3_BUCKET_NAME}/travis-builds/$1 _
        if cmp $1 _
        then
          echo === UPLOADED $1 ===
        else
          echo === UPLOAD $1 FAILED ===
          exit 1
        fi
      }

      for i in $OS_ID/*; do upload $i; done

      # !!! This is where we would put any finalization code for the upload.
      # Here's what Ren-C's finalization does, to provide the hash of the
      # latest executable for each version that successfully uploaded.
      #
      # echo -n "${GIT_COMMIT_SHORT}" > ${OS_ID}/last-deploy.short-hash
      # upload ${OS_ID}/last-deploy.short-hash

# vim: set et sw=2:
